### ISSUE TITLE
Interaction with beforeEach

### ISSUE THREAD

**Issue by macobo** [tatyshev/given2#24]
Hi! 

First of all, thanks for this wonderful library! We've gotten a ton of milage out of it at https://eagronom.com as it allows us to write yarn tests in a really similar way to how we structure our rspec tests. We experimented with a couple of other tools that promised the same result, but they all fell short.

One problem we've run into is with how the library interacts with `beforeEach`. In tests where we set up mock return values or set up document.body.innerHTML, the following option does not work:

```javascript
const someMock = jest.fn()

describe('somefunction()', () => {
  beforeEach(() => {
    someMock.mockReturnValue(given.returnValue)
  })

  given('returnValue', () => 1)
    
  it('returns given result', () => {
    expect(someMock()).toEqual(1)
  })
})
```

This fails:

```
  somefunction()
    ✕ returns given result (8ms)

  ● somefunction() › returns given result

    expect(received).toEqual(expected)

    Expected value to equal:
      1
    Received:
      undefined
```

It seems as if the beforeEach is run before given2 lazy values are set up, causing errors. I assue it's because how given2 uses beforeEach under the hood as well.

The workaround is to do this instead:

```javascript
given('!mymock', () => someMock.mockReturnValue(1))
```

However this solution, it gets really cumbersome in larger tests.

Is there a better way to being able to use given2 and beforeEach together?

**Comment by tatyshev** [comment]
`given2` declarations are not intended to be called inside a `beforeEach` hook, because `given2` itself is wrapper around `beforeEach/afterEach` hooks. Another workaround might be the following usage example:

```js
describe('somefunction()', () => {
  given('subject', () => {
    const someMock = jest.fn()
    someMock.mockReturnValue(given.returnValue)

    return someMock();
  })

  given('returnValue', () => 1)
    
  it('returns given result', () => {
    expect(given.subject).toEqual(1)
  })
})
```

**Comment by maboesanman** [comment]
I felt that this was a significant enough hinderance for my usage that I build a similar library that does things very differently under the hood. Interaction with beforeEach is a primary design goal, as I needed this to do things like click a component that was declared with given()
[check it out here](https://github.com/enova/givens)
